---
#- hosts: quantum
- hosts: localhost
  gather_facts: yes
  sudo: true
  vars:
    hostname:       quantum
    os_username:    'phill'
    common_install_media: false
    common_install_dev_utils: false

  pre_tasks:
    - shell: echo 'Starting...'
    
  roles:
    - patrick-hill.common
    - patrick-hill.nfs-mounts
    - patrick-hill.whatpulse
    - patrick-hill.chrome
    - patrick-hill.vagrant
    - patrick-hill.virtualbox

  post_tasks:
    - shell: echo 'Done'

